"""Add column ChatMessage

Revision ID: 9e92e7f6ad79
Revises: 5aac89d7b349
Create Date: 2025-10-23 06:04:25.910011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e92e7f6ad79'
down_revision: Union[str, Sequence[str], None] = '5aac89d7b349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('content', sa.String(), nullable=False))
    op.add_column('chat_message', sa.Column('attachement', sa.String(), nullable=True))
    op.drop_column('chat_message', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chat_message', 'attachement')
    op.drop_column('chat_message', 'content')
    # ### end Alembic commands ###
