"""Add column parcel

Revision ID: dae3a0c6ee36
Revises: a9db1725f3ff
Create Date: 2025-10-19 07:57:24.624969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae3a0c6ee36'
down_revision: Union[str, Sequence[str], None] = 'a9db1725f3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('geometry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'geometry')
    # ### end Alembic commands ###
